### ISSUE TITLE
Divide by zero issue in doors and chests

### ISSUE THREAD

**Issue by ObsidianDust** [Aetherial-Labs/HammersRingingFall#2]
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.16.4 (Stable)
Loaded Mods: advancedsmithing@1.2.0, chiseltools@1.3.1, collabclasses@3.0.3, dragonflies@1.2.0, expandedfoods@1.5.3-pre.4, fieldsofgold@1.1.13, foundrymod@1.0.0, glassmaking@1.2.0, hammersringingfall@1.1.2-rc.1, knappingmastery@1.0.1, potatoes@1.0.8, moredrygrass@0.2.0, moreminerals@1.0.2, leadroof@1.1.1, preservationmod@1.0.0, primitivesurvival@2.8.0, qptech@1.7.6, viescraftmachines@1.17.0, game@1.16.4, carrycapacity@0.6.5, farmlife@1.2.3, fromgoldencombs@1.3.11, lichen@1.6.1, medievalexpansion@3.7.1, moreanimals@1.2.2, morepiles@1.2.0, petai@1.3.7, prospectorinfo@3.1.2, stonequarry@1.6.5, usefulstuff@2.3.2, creative@1.16.4, survival@1.16.4, wildfarming@1.2.8, xrowboat@0.0.3, campaigncartographer@2.1.3, bricklayers@0.9.0, feverstonehorses@1.2.6, packanimals@1.0.1, wildcraft@1.2.1
2022-03-31 11:19:32 AM: Critical error occurred
System.DivideByZeroException: Attempted to divide by zero.
   at Vintagestory.API.Client.SlideshowGridRecipeTextComponent.RenderInteractiveElements(Single deltaTime, Double renderX, Double renderY)
   at Vintagestory.API.Client.GuiElementRichtext.RenderInteractiveElements(Single deltaTime)
   at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime)
   at Vintagestory.API.Client.GuiDialog.OnRenderGUI(Single deltaTime)
   at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _4Bi1AGVssrIO0El8b8ygdS9FIfm._LvzIyYpsQCoC78JubjSO0HCjtTg(Single )
   at _lAuHsYOBOAjBMdATFXwLUtH7N00._JvY4M2412YZu1OS3Ull8wgZBu1j(Single )
   at _lAuHsYOBOAjBMdATFXwLUtH7N00._KmBeEx15nyyLrVqNDW6geSArpNr(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at _TRhArnJABwZoV9Vt7Ld2l65Xzgg._mhlr8s7wtMvxaJGpVy2Ag90jUBK(_3HJA5NvAIx31LXjscc3HGjXaR6q , String[] )
   at _q0zAVOrWbMX04rMA9G3HIFVuGjA._mhlr8s7wtMvxaJGpVy2Ag90jUBK(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2022-03-30 1:13:21 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1404892564174130458, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.4.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Timot\AppData\Local\Temp\RDR4936.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4947.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4948.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4965.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4985.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 2814f749-30a3-47a9-8bc8-43a775027bd8
Report Status: 268435456
Hashed bucket: 7bdc35654b5a35c0737f2e57fb2fcd1a
Cab Guid: 0 }
--------------
{ TimeGenerated = 2022-02-28 8:44:04 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1404892564174130458, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.4.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Timot\AppData\Local\Temp\RDR82FA.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER830A.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER830B.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8329.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8349.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 2fd97e91-f5f1-4fc8-8189-481b644b9249
Report Status: 268435456
Hashed bucket: 7bdc35654b5a35c0737f2e57fb2fcd1a
Cab Guid: 0 }
--------------
{ TimeGenerated = 2022-01-29 8:42:44 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1302431364789752868, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.16.1.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Timot\AppData\Local\Temp\RDRB13A.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB14A.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB15B.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB169.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB199.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: a1f29192-3550-42d6-9ba6-bfdeac93fd38
Report Status: 268435456
Hashed bucket: 63f31e0847fe955382132a6cfa9ed424
Cab Guid: 0 }

**Comment by VinterNacht** [comment]
I believe this is resolved in 1.2.1, if not, will be for 1.2.2
